### ISSUE TITLE
Eight public functions let OverflowError and AttributeError escape, where the contract says BTClibValueError

### ISSUE THREAD

**Issue by fametrano** [btclib-org/btclib#690]
btclib states its exception contract in the tree, twice:

> `BTClibValueError` subclasses `ValueError`, so an `except ValueError`
> caller catches this too — `network.py:446`

> a `UnicodeDecodeError` let out would fly past every caller written to
> catch `BTClibValueError` — `bech32.py:109`

Eight public functions break it. Given an object that its own
`assert_valid` refuses, they raise something that is **not** a
`ValueError` — `OverflowError` is an `ArithmeticError`, `AttributeError`
is neither — so it flies past exactly the handler the contract tells a
caller to write.

Reproduced, not read:

```console
script / sig_hash
  sig_hash.from_tx([bad prevout], tx, 0, 0x01)     LEAKS OverflowError: int too big to convert
  sig_hash.segwit_v0(script, tx, 0, 0x01, 2**64)   LEAKS OverflowError: int too big to convert
  sig_hash.legacy(script, <bad tx>, 0, 0x01)       LEAKS OverflowError: int too big to convert
  sig_hash.taproot(<tx>, 0, [bad prevout], ...)    LEAKS OverflowError: int too big to convert
block
  merkle_root_and_mutated_from_transactions([bad]) LEAKS OverflowError: int too big to convert
  mining.candidate_block_header([bad])             LEAKS OverflowError: int too big to convert
  Block.assert_valid_contextual(<bad context>)     LEAKS AttributeError: 'str' object has no attribute 'tzinfo'
psbt
  ecdsa_sig_hash(<bad psbt>, 0)                    LEAKS OverflowError: int too big to convert
```

The objects used: `TxOut(2**64, spk, check_validity=False)`, whose
`assert_valid` raises `BTClibValueError: invalid satoshi amount`;
`Tx(version=2**32, …, check_validity=False)`, whose `assert_valid` raises
`BTClibValueError: invalid version`; and `BlockContext(height="not an
int", now="not a datetime", check_validity=False)`, whose `assert_valid`
raises `BTClibTypeError`. Each is what the library itself would refuse,
handed to a public function that never asks.

## Why it happens, and what the fix is not

These paths serialize the same objects many times and pass
`check_validity=False` throughout — deliberately, and rightly: that is
what the flag exists for, and flipping it would pay the check once per
serialization. The bare exception is what is left when the check is
skipped *and* nobody validated at the door.

So the fix is the rule of #684: **validate once, at the public entry**,
and leave the private machinery below exactly as it is. That turns each
of the eight into the refusal the caller is already written to catch,
and costs one `assert_valid` per call rather than one per serialization.

## Severity

None of this is reachable from parsed input: `parse` and the
constructors validate by default, so it takes a caller that builds the
object itself and passes `check_validity=False`. That is a supported
thing to do — `tests/check_validity_test.py` exercises the flag across
the library — and the consequence is a crash of the wrong type rather
than a wrong answer. Worth fixing as a contract breach, not as a
vulnerability.

`ssa` batch verification is the one case where the missing check changes
an *answer* rather than an exception type; that is #688, filed
separately.

**Comment by fametrano** [comment]
Five of the eight are closed by bde9e8ed (PR #701). Two of this issue's premises did not survive the suite, which is what decided the shape of the fix:

**The amount is a signed `CAmount`, so `valid_sats_amount` is the wrong instrument.** `test_the_bip143_amount_is_a_signed_camount` asserts that `-1` is what eight `ff` octets mean and that the preimage commits to them either way (issue #388) — so refusing the money range would refuse a preimage Core writes. What actually leaked is an integer no eight-byte signed field can hold, and that is what `_assert_valid_camount` refuses: `segwit_v0`'s amount, and every prevout amount `taproot` and `from_tx` commit to. Their `script_pub_key`s are asked what `TxOut` now asks of a pre-built one (#694).

`Block.assert_valid_contextual` and `ecdsa_sig_hash` took the object check, `BlockContext.assert_valid` and `Psbt.assert_valid` being what they had no call to.

## The two that are left, and why they are not lines to add

- **`merkle_root_and_mutated_from_transactions` does not judge on purpose.** `test_merkle_root_and_witness_commitment_serialize_without_judging` pins that it serializes with `check_validity=False` rather than raising on the second transaction's own account: a block's validity is `Block.assert_valid`'s, once, outside the loop. Validating inside it broke that test. `mining.candidate_block_header` inherits the same, delegating to it.
- **`legacy` leaks on `tx.version`, and `Tx.assert_valid` is the wrong instrument too.** Eight tests in `tests/script/sig_hash_script_code_test.py` hand it synthetic transactions — a coinbase script of invalid size among them — to exercise the script code, and full validation refuses all eight.

Both want the same thing, and it is a decision rather than a line: **refuse the width where the integer is serialized**, so that an out-of-range `version`, `lock_time` or amount becomes a `BTClibValueError` at the boundary instead of an `OverflowError`, without any caller having to judge an object it was handed. That closes these two and would have closed the other five as a side effect, so it is worth deciding before more entries grow checks of their own.

Left open for that decision. The five above are done.
